Repository HuHu24/huhu-sovellus, pull requests merged in 2024-05, with the labels that each got.

#156 Subcamp ja subcamp sivu refactor
  src/app/admin/notifications/page.tsx
  src/app/admin/releases/[releaseId]/page.tsx
  src/app/admin/releases/new/page.tsx
  src/app/api/auth/claims/subcamp/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/settings/page.tsx
  src/app/subcamp/page.tsx
  src/components/admin/releases/releases.tsx
  src/components/notificationPopup.tsx
  src/firebaseAdmin.ts
  src/messaging.ts
  src/utils/getTimetable.ts
Labels: enhancement, refactor

#164 feat: made cafe activities
  src/app/activities/cafe/page.tsx
  src/app/api/joinEvent/route.ts
  src/components/navbar.tsx
  src/utils/getCafeTimetable.ts
Labels: enhancement

#167 Priveledge & api updating
  README.md
  src/app/admin/access/page.tsx
  src/app/admin/notifications/page.tsx
  src/app/admin/page.tsx
  src/app/admin/releases/[releaseId]/page.tsx
  src/app/admin/releases/new/page.tsx
  src/app/api/admin/claims/route.ts
  src/app/api/admin/messaging/route.ts
  src/app/api/admin/releases/route.ts
  src/app/api/auth/joinEvent/route.ts
  src/app/api/auth/subcamp/route.ts
  src/app/settings/page.tsx
  src/app/subcamp/page.tsx
  src/components/admin/chat/chat.tsx
  src/components/daysTimetable.tsx
  src/middleware.ts
Labels: documentation, refactor

#170 Update signup logic on /subcamp
  src/app/api/auth/signup/route.ts
  src/app/subcamp/page.tsx
  src/components/notificationPopup.tsx
  src/firebase.ts
  src/firebaseAdmin.ts
Labels: enhancement, refactor

#174 Huollon palautelomake #172
  src/app/admin/access/page.tsx
  src/app/admin/page.tsx
  src/app/admin/upkeep/page.tsx
  src/app/api/admin/claims/route.ts
  src/app/page.tsx
  src/components/reportToUpkeep.tsx
  src/middleware.ts
  src/types/flaw.ts
Labels: enhancement
