Repository HuHu24/huhu-sovellus, pull requests merged in 2024-01, with the labels that each got.

#13 feat: Created nextjs.yml
  .github/workflows/nextjs.yml
Labels: enhancement

#15 GitHub actions bug #14
  .github/workflows/build-and-test.yml
  .github/workflows/deploy.yml
  next.config.js
Labels: bug, enhancement

#16 GH Pages deployment fix #14
  .github/workflows/deploy.yml
Labels: bug

#17 Prettier
  .eslintrc.json
  .github/workflows/build-and-test.yml
  .github/workflows/deploy.yml
  .prettierignore
  .prettierrc.json
  CONTRIBUTING.md
  next.config.js
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: enhancement

#18 GitHub pages deployment fix
  .github/workflows/deploy.yml
  next.config.js
Labels: bug

#19 Navbar #4
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/navbar/navbar.tsx
  src/components/navbar/navbarMenu.tsx
  tailwind.config.ts
Labels: enhancement

#21 Navbar fix
  package-lock.json
  src/components/navbar/navbar.tsx
Labels: bug

#42 Added the aikataulu page
  src/app/page.tsx
  src/app/timetable/page.tsx
  src/components/daysTimetable.tsx
  src/components/navbar/navbar.tsx
  src/components/tiedote.tsx
Labels: enhancement

#43 Navbar fix/enhancement #37
  package-lock.json
  src/app/globals.css
  src/components/navbar/navbar.tsx
  tailwind.config.ts
Labels: enhancement

#55 Subcamp page #2
  next.config.js
  public/subcamp_page_background.svg
  src/app/subcamp/page.tsx
  tailwind.config.ts
Labels: enhancement

#59 fix: Aaro kusi mergen ja piti nyt lisää toi smallPhone et IPhone 5 en…
  tailwind.config.ts
Labels: bug

#64 feat: Moved height calculation from page files to global layout file
  CONTRIBUTING.md
  src/app/layout.tsx
  src/app/page.tsx
  src/app/releases/page.tsx
  src/app/timetable/page.tsx
  src/components/navbar/navbar.tsx
  src/components/navbar/navbarButton.tsx
Labels: enhancement

#69 feat: added firebase
  firestore.indexes.json
  firestore.rules
  package-lock.json
  package.json
  public/404.html
  public/index.html
  remoteconfig.template.json
  src/firebase.ts
  storage.rules
Labels: enhancement, Sovelluksen ulkopuolinen

#71 feat: firebase admin sdk configured
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/app/layout.tsx
  src/env.ts
  src/firebaseAdmin.ts
Labels: enhancement

#74 Admin login #27
  .env.example
  .gitignore
  next.config.js
  src/app/api/auth/claims/route.ts
  src/app/api/auth/route.ts
  src/app/auth/layout.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/components/navbar/navbar.tsx
  src/env.ts
  src/firebase.ts
  src/middleware.ts
Labels: enhancement, Sovelluksen ulkopuolinen

#79 Bug: Allowed scrolling on small screens
  src/app/page.tsx
Labels: bug
