Repository HuHu24/huhu-sovellus, pull requests merged in 2024-04, with the labels that each got.

#114 81 push notificatioiden setuppaaminen
  .env.example
  .gitignore
  README.md
  package.json
  public/firebase-messaging-sw.js
  src/app/api/auth/claims/subcamp/route.ts
  src/app/layout.tsx
  src/app/subcamp/page.tsx
  src/firebase.ts
  src/firebaseAdmin.ts
  src/messaging.ts
Labels: bug, enhancement, refactor

#123 Aikataulu ulkopuolisella datalla #42
  src/app/page.tsx
  src/app/timetable/page.tsx
  src/components/daysTimetable.tsx
Labels: enhancement

#124 fix: Horizontal navbar closes when needed
  src/components/navbar.tsx
Labels: bug

#121 Stuff
  .env.example
  .eslintrc.json
  README.md
  next.config.js
  package-lock.json
  package.json
  public/swe-worker-4da67dda9bc18c53.js
  src/app/admin/access/page.tsx
  src/app/admin/chat/[chatId]/page.tsx
  src/app/admin/chat/page.tsx
  src/app/admin/releases/[releaseId]/page.tsx
  src/app/admin/releases/new/page.tsx
  src/app/admin/releases/page.tsx
  src/app/chat/page.tsx
  src/app/page.tsx
  src/app/releases/page.tsx
  src/app/timetable/page.tsx
  src/components/admin/access/accessList.tsx
  src/components/admin/chat/chat.tsx
  src/components/admin/releases/menuButton.tsx
  src/components/admin/releases/releases.tsx
  src/components/admin/releases/sort.tsx
  src/components/adminRelease/releases.tsx
  src/components/daysTimetable.tsx
  src/components/message.tsx
  src/components/navbar.tsx
  src/components/release/release.tsx
  src/components/release/release_frontpage.tsx
  src/components/release/releases.tsx
  src/components/releases.tsx
  src/firebase.ts
  tsconfig.json
Labels: bug, documentation, enhancement, refactor, dependencies

#132 Sivu navbar ei sulkeudu kun painetaan ala navbarista #122
  src/components/navbar.tsx
Labels: bug

#134 fix: Improvements to chat
  src/app/chat/page.tsx
Labels: enhancement

#131 Made the frontpage promise all
  src/app/subcamp/page.tsx
Labels: bug, enhancement

#139 119 admin uusi ilmoitus
  src/app/admin/notifications/page.tsx
  src/app/api/auth/claims/subcamp/route.ts
  src/app/api/messaging/route.ts
  src/firebaseAdmin.ts
  src/middleware.ts
Labels: enhancement, refactor

#145 143 tekijävaeltaja subcamp
  public/swe-worker-4da67dda9bc18c53.js
  src/app/api/auth/claims/route.ts
  src/app/api/auth/job/route.ts
  src/app/subcamp/page.tsx
Labels: enhancement, refactor

#149 147 settings page
  src/app/api/auth/claims/subcamp/route.ts
  src/app/api/auth/job/route.ts
  src/app/api/auth/notifications/route.ts
  src/app/settings/page.tsx
Labels: enhancement, refactor

#148 107 tiedotteet finaltouches
  src/app/admin/releases/[releaseId]/page.tsx
  src/app/admin/releases/new/page.tsx
  src/app/admin/releases/page.tsx
  src/app/page.tsx
  src/app/releases/[releaseId]/page.tsx
  src/app/releases/page.tsx
  src/components/admin/releases/menuButton.tsx
  src/components/admin/releases/releases.tsx
  src/components/admin/releases/sort.tsx
  src/components/releases.tsx
  src/firebase.ts
  src/types/menuButton.ts
  src/types/releases.ts
Labels: enhancement, refactor

#152 Sovellusmatskut #118
  src/app/info/safety/page.tsx
  src/app/info/subcamp/page.tsx
  src/app/info/ttp/page.tsx
  src/app/page.tsx
  src/components/navbar.tsx
Labels: enhancement

#153 More stuff
  src/app/api/auth/route.ts
  src/app/page.tsx
  src/app/releases/[releaseId]/page.tsx
  src/app/releases/page.tsx
  src/app/timetable/page.tsx
  src/components/admin/releases/releases.tsx
  src/components/releases.tsx
  src/firebase.ts
  src/firebaseAdmin.ts
  src/types/releases.ts
  src/types/timetable.ts
  src/types/user.ts
  src/utils/formatDateTime.ts
  src/utils/getRelease.ts
  src/utils/getReleases.ts
  src/utils/getTimetable.ts
  src/utils/getUser.ts
Labels: bug, enhancement, refactor
